---
title: "ASSETS"
author: "Jess Zhang"
date: "May 2, 2018"
output: 
  md_document:
      variant: markdown_github
---

# Input
All data files are stored under bankingclientsprofile/data folder.
1. bank-additional-full.csv -- The original data downloaded from http://archive.ics.uci.edu/ml/datasets/Bank+Marketing.  This data set contains Bank of Portugal's telemarketing data in total of 14,828 records.  
2. bank-additional-names.txt -- contains the column names and data format for all 21 columns in the data file.  
3. updatedbankingdata.csv -- This file contains a clean version of the bank-additional-names.txt.  All training will be run on data from this file.
  Changes in this file includes:  
  * The information of date or time of the call has been removed.
  * All missing data has been replaced with dominant majority value. 
  * All duplicated rows have been removed from the dataset.
  * The file format has been changed from semicolon separated file to comma separated file for excel.
4. next_campaign_data.csv -- contains data from future campaign for predicting purposes.

## Data
1. package "campaignModel" -- the package that contains necessary code and data to predict future results.
2. pkgs/campaignModel/data/model.RDS -- the model we will use to predict future results
  
## Code
All code files are stored under bankingclientsprofile/srv folder.  
1. loaddata.R -- This file contains the code to load the data from the original data file (bank-additional-full.csv) and to clean the data for modeling.
2. initialanalysis.R -- The naive analysis is run from this file.  A histogram is generated from this block of code and is stored and displayed in project-performance.Rmd.
3. training.R -- This file contains the majority of the code for training and modeling.  Multiple algorithms are run and compared.

# Outputs:  
1. five graphs are generated for this project:
  -The initial output-age analysis histogram Naive-age.jpeg
  -The ROC curve for glm, randomForest and svm.
  -A graph combines the ROC for three algorithm for comparison and analysis.

2. crMatrix.txt -- contains the confusion matrix for all three algorithms.

3. project-performance.pdf, project-performance.html, and project-performance.docx -- project performance analysis in three different formats.